{% set name = "pysimplegui" %}
{% set version = "4.15.2" %}
{% set styledName = "PySimpleGUI" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/b2/d0/c20c020af7d2e61ab61ba2b2c9299b5eda75ab5615498733f1a04d8996c1/PySimpleGUI-{{ version }}.tar.gz"
  sha256: "91cf79070de893439cedb4d6689fc0d768f30d3b6e289634e5f81cd5caf25ff2"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - PySimpleGUI

about:
  home: "https://github.com/PySimpleGUI/PySimpleGUI"
  license: "LGPL-3.0"
  license_family: "LGPL"
  license_file: "license.txt"
  summary: "GUI SDK Launched in 2018 Actively developed and supported. Super-simple to create custom GUI's.  Python 2.7 & 3 Support. 100 Demo programs & Cookbook for rapid start. Extensive documentation. Examples using Machine Learning(GUI, OpenCV Integration,  Chatterbot), Rainmeter Style Floating Desktop Widgets, Matplotlib + Pyplot integration, add GUI to command line scripts, PDF & Image Viewer. Great for beginners as well as advanced GUI programmers"
  doc_url: "http://www.pysimplegui.org/"
  dev_url: "https://github.com/PySimpleGUI/PySimpleGUI"

extra:
  recipe-maintainers:
    - agcopenhaver
