travis:
  secure:
    BINSTAR_TOKEN: rwln/q9UnSwiZAdnNS8/0jtXi0d92iYNhQjziF9Pr3cu0kUZI/o29XOs25VK3mKwKv19n5jleQcv3mYfPA58hlqV9DESRKb7me1/gUK/7vXWLXjsF04voOwbAH6HBPe99vW675c7Dc3nQ9dqovDzklRkEssdia9JXb+lb3qzLSBer49eDGLize6rQ+9j93SYk/qwO4zzrzC95A1SlEzI0ZpAuRyHKu+tR85MrSoeJ1ZeyveAsTmxgCEMQzwYmDtjLlDWbhWGqVS+dpoxfLerbiIuE8ebiOLzPlmmiWvyNIPtEuYFDV8UOTuO4wWZ4HNTAxBWxKLr7MoSw3vo423g5F96QplyrtM6e/aw3CIO+wkZGybfFBnb+zRjCS3b6+YdfNu6vYtjrFAyT1BfHaXWVEqO8AATx3iSBGr6J821kiNvOzwKe4zFi9GRj0ktgWkfUr5H0HDCELue6dv+P7VDbhZIrh4RaJgYgrThmw2Kx8xi1oZRQVl0895a3ldw/2K6rRYXlB1ATG3tk+fQOoPDpQPQ3X/ENUQz2o6LGE5ChAAorpLLnsEY5dLOoqhJq4arVY3tqxuBf7/OnM1bFqugJj62gdToDzzcsGg4H8FQ91xLl7qA0Iwm/P2A5zQ4wYGKJCEdwIkdg9oJq/8d19cVhSIZxJBzOBr3NzSo5ROrCdI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
