travis:
  secure:
    BINSTAR_TOKEN: jDJ1GM6HSX9l2+BDVzTRlCwIabcCFF84x3ciR7KNcti//axuru83qLYKDnNRwfHxSjdzEZQl87zKqRyb62zTQOUss7w66qIWkcUXYAi3uE/WsIuQV38u8Ea1GWQqFgYiVkzdCf+vOlytTnySPKjuuDoYDk8P+Q0DnroFJMXv7FjiBhzH0uBqh19bfXsTziB3f2Ztxvzex4x084e+EIFverc+mbEws9vVy+6L/gHgQy+HWx6KNQYMl1gjSOZk+JZGDsuz50tFXvl7oCNh7HbqvaaPjuNrkAdwqDarPhKCfSuOOqd1hF2JUlNKlh0VyJ5dAPs7UKcuVsclT8UZQeiNDRQ9DIAdJDb5pMrSNc5Mqs4JA4G3TuWwI3YX7/a6uUF/TqqK6zKNapFtpLxwX/0AotaSehauIrzOPUF/wHOwGOzsmRf1JLXWupNj5RszcfaYGz4ASPSauh6Z2zo/peisOAIoPWeMvmqBYz2lOMRmm9a/BesUxvEAXorOuIELxOi7N53/mEBq/C8yaw3AoGMDJrE1iNBhHSxIyzBNJoxgowHz3sJ7Jg4HpbUC9k0wOADhTuhWdkvZSrEDnnOLvL589cKwGeI4IN7P3NYNgnjnwh0g8N3NevfAvoJI4IkcQBI18F+d4EmKE9fSFa6Yma/DCE/sv2m84/cVBmBx8RnqtVE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
