travis:
  secure:
    BINSTAR_TOKEN: sK6v3Ac0ZnP9w5UVVs9Df32g+NP88/5J4zIhUhXEofyjWjeHNrrS6eo+pvL22UlsVkpdBoM+/zYe56SR5uyyN+ocR+Bizch2pLXdP26qoYFL9P+V5pAwtUstAL3GOLP0pR7YxOGGQIerkGWfoksO1YAWMJlECkZ0pgV0ZatPD1M2Faqyfq2WRJGqM6pBPIp9k8v5VrI7L1JryEJlGRswQE2w5XNjy9jJ11mfuAdqJY3yc9ZdMlER8X2RXCMZWjnOe8YWAIOBp+VXAsZy4J9XCAdTJMhezJHokzxH9xcctT93BrNLSjVc2ilfXZ0y4A6qqErIITxvN2I13V1tcASn5XUwp6n3pObQjmBLl/Zn3GhhwFSHYKnXvlsio+MCwU5F8FaHT5JKeru94+zwq+qfSZKQr7hznyT1fAWR/dg4PWMK5LKUZrXNuYphBXaq/DC7u4NIxe82pkUAnycVG73idFI6ZnHqClBni8M/n2VzsS3++bc3nNeFDfmtOM1HWGcZ9+X53Ff6SAcPIqel6pSvwjIyNzEIkdLWdlwR2OiFRo040QiQxFvFqUTFM71FkdWebh8WK4HFYVOqseazz598UJo7MjA2Dn0VMiDrELwG+lJ2g4Pt/D6FR9j4DAxzFwIBuPKbt0U9sLDIkFmIfqwGFM7Kf940V/8kkLHlxXez3Rw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
